spring:
  application:
    name: spring-example
  datasource:
    url: jdbc:mysql://localhost:3306/progetto_medusa
    username: root
    password: admin_mysql01
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  licensed-apps:
    - local-postman
    - app2
    - app3

logging:
  level:
    com: DEBUG

user-application:
    name: user-service